//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Yonetimi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DUYURU_YORUM
    {
        public int ID { get; set; }
        public byte DUYURU_ID { get; set; }
        public int UYE_ID { get; set; }
        public string MESAJ { get; set; }
        public System.DateTime TARIH { get; set; }
        public bool ONAY { get; set; }
    
        public virtual TBL_DUYURULAR TBL_DUYURULAR { get; set; }
        public virtual TBL_UYELER TBL_UYELER { get; set; }
    }
}
