//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Yonetimi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DUYURULAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DUYURULAR()
        {
            this.TBL_DUYURU_YORUM = new HashSet<TBL_DUYURU_YORUM>();
        }
    
        public byte ID { get; set; }
        public string KATEGORI { get; set; }
        public string ICERIK { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> LikeSayısı { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DUYURU_YORUM> TBL_DUYURU_YORUM { get; set; }
    }
}
