//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Yonetimi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_UYELER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_UYELER()
        {
            this.TBL_CEZALAR = new HashSet<TBL_CEZALAR>();
            this.TBL_HAREKET = new HashSet<TBL_HAREKET>();
        }
    
        public int ID { get; set; }

        [Required(ErrorMessage = "Ad ve soyad bo�� ge��ilemez")]
        [StringLength(20, ErrorMessage = "Ad 20 karakterden fazla olamaz")]
        public string AD { get; set; }

        [StringLength(20, ErrorMessage = "Soyad 20 karakterden fazla olamaz")]
        [Required(ErrorMessage = "Soyad bo�� ge��ilemez")]
        public string SOYAD { get; set; }

        public string MAIL { get; set; }

        [Required(ErrorMessage = "Kullan��c�� ad�� bo�� ge��ilemez")]
        public string KULLANICIADI { get; set; }

        [Required(ErrorMessage = "��ifre bo�� ge��ilemez")]
        [StringLength(10, ErrorMessage = "Şifre 10 karakterden fazla olamaz")]
        public string SIFRE { get; set; }

        public string FOTOGRAF { get; set; }

        [Required(ErrorMessage = "Telefon numaras�� bo�� ge��ilemez")]
        public string TELEFON { get; set; }

        public string OKUL { get; set; }

    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CEZALAR> TBL_CEZALAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_HAREKET> TBL_HAREKET { get; set; }
    }
}
