//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Yonetimi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_PERSONEL
    {
        public byte ID { get; set; }
        [Required(ErrorMessage ="Personel adý ve soyadý boþ geçilemez")]
        public string PERSONEL { get; set; }
    }
}
